name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: async-code-web
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: async-code-web/package-lock.json
      - run: npm ci
      - run: npm run build

  backend-static-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Static analysis
        run: python -m compileall -q server
